version: '3.9'

services:
  treinai:
    image: treinai
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
      - rabbitmq
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=db;Database=Treinai;User=sa;Password=YourStrong!Passw0rd;"
      SMTP__UserName: ${SMTP__UserName}
      SMTP__Nome: ${SMTP__Nome}
      SMTP__Host: ${SMTP__Host}
      SMTP__Senha: ${SMTP__Senha}
      SMTP__Porta: ${SMTP__Porta}
      RabbitMQ__Host: ${RabbitMQ__Host}
      RabbitMQ__UserName: ${RabbitMQ__UserName}
      RabbitMQ__Password: ${RabbitMQ__Password}

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - treinai-db-data:/var/opt/mssql

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"

volumes:
  treinai-db-data:



